[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  OPENAI_API_KEY = "your-openai-api-key"
  GITHUB_TOKEN = "your-github-token"

[[plugins]]
  package = "@netlify/plugin-nextjs"
